#!/bin/bash
# Manual deployment instructions for Cloudflare authentication fix

echo "📋 Manual deployment instructions for listerino.com"
echo "=================================================="
echo ""
echo "Since SSH key authentication failed, please follow these manual steps:"
echo ""
echo "1. Copy the patch file to your server:"
echo "   Option A: Use password authentication (if enabled):"
echo "   scp -o PreferredAuthentications=password cloudflare-auth-fix.patch root@137.184.113.161:/tmp/"
echo ""
echo "   Option B: Copy the contents manually:"
echo "   - SSH into your server: ssh root@137.184.113.161"
echo "   - Create the patch file: nano /tmp/cloudflare-auth-fix.patch"
echo "   - Copy and paste the contents from cloudflare-auth-fix.patch"
echo ""
echo "2. Apply the patch on your server:"
echo "   ssh root@137.184.113.161"
echo "   cd /var/www/listerino"
echo "   patch -p1 < /tmp/cloudflare-auth-fix.patch"
echo ""
echo "3. Clear caches and restart services:"
echo "   sudo -u www-data php artisan optimize:clear"
echo "   sudo -u www-data php artisan config:cache"
echo "   sudo -u www-data php artisan route:cache"
echo "   sudo -u www-data php artisan view:cache"
echo "   systemctl restart php8.3-fpm"
echo ""
echo "4. Test the fix:"
echo "   - Visit https://listerino.com/admin/media"
echo "   - Try uploading an image"
echo ""
echo "Alternative: If you have GitHub access set up on the server:"
echo "   1. Commit and push these changes to your repository"
echo "   2. Pull the changes on the server:"
echo "      cd /var/www/listerino"
echo "      git pull origin main"
echo "      # Then run the cache clearing commands above"