version: '3.8'

services:
  # Laravel Backend API
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: laravel-app
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - laravel
    # depends_on:
    #   - db
    env_file:
      - .env.docker
    environment:
      - DB_HOST=docker.for.mac.localhost
      - DB_PORT=5432
      - DB_DATABASE=illum_local
      - DB_USERNAME=ericslarson
      - DB_PASSWORD=
      - SPA_MODE=true

  # Vue Frontend SPA
  frontend:
    image: node:20-alpine
    container_name: laravel-frontend
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5174:5174"
    networks:
      - laravel
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    # Don't set VITE_API_URL so requests go through Vite proxy

  # PostgreSQL Database - Commented out since we're using local PostgreSQL
  # db:
  #   image: postgres:15
  #   container_name: laravel-db
  #   restart: unless-stopped
  #   environment:
  #     POSTGRES_DB: laravel
  #     POSTGRES_USER: laravel
  #     POSTGRES_PASSWORD: secret
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"
  #   networks:
  #     - laravel

  # Nginx Web Server
  nginx:
    image: nginx:alpine
    container_name: laravel-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel
    depends_on:
      - app

networks:
  laravel:
    driver: bridge

# volumes:
#   postgres_data: