#!/bin/bash
# Production Deployment Commands for listerino.com
# Run these after GitHub Actions deployment completes

echo "=== Production Deployment Commands ==="
echo "SSH to production server:"
echo "ssh root@137.184.113.161"
echo ""
echo "Once connected, run these commands:"
echo ""
echo "# 1. Navigate to application directory"
echo "cd /var/www/listerino"
echo ""
echo "# 2. Run database migrations (IMPORTANT: Many new migrations)"
echo "docker exec -w /app listerino_app php artisan migrate --force"
echo ""
echo "# 3. Clear all caches"
echo "docker exec -w /app listerino_app php artisan cache:clear"
echo "docker exec -w /app listerino_app php artisan config:clear"
echo "docker exec -w /app listerino_app php artisan route:clear"
echo "docker exec -w /app listerino_app php artisan view:clear"
echo ""
echo "# 4. Optimize application"
echo "docker exec -w /app listerino_app php artisan optimize"
echo ""
echo "# 5. Enable PostGIS extension (if not already enabled)"
echo "docker exec -u postgres listerino_db psql -d listerino -c 'CREATE EXTENSION IF NOT EXISTS postgis;'"
echo ""
echo "# 6. Check application status"
echo "docker exec -w /app listerino_app php artisan about"
echo ""
echo "# 7. Check container status"
echo "docker ps"
echo ""
echo "# 8. View recent logs if needed"
echo "docker logs --tail 50 listerino_app"
echo ""
echo "# 9. If containers need restart"
echo "docker-compose -f docker-compose.production.yml down"
echo "docker-compose -f docker-compose.production.yml up -d"
echo ""
echo "=== Important Notes ==="
echo "- Multiple new migrations for sections, geospatial, saved collections"
echo "- PostGIS extension must be enabled for map features"
echo "- Mapbox API key must be set in .env (VITE_MAPBOX_ACCESS_TOKEN)"
echo "- Clear browser cache after deployment"