name: Test Server Connection

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    environment: Production Server
    
    steps:
    - name: Test SSH Connection
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: 22
        script: |
          echo "✅ SSH Connection successful!"
          echo "Server: $(hostname)"
          echo "User: $(whoami)"
          echo "Directory: $(pwd)"
          echo ""
          echo "Checking Docker services:"
          docker ps --format "table {{.Names}}\t{{.Status}}"
          echo ""
          echo "Checking application directory:"
          ls -la /var/www/listerino | head -10
          echo ""
          echo "Checking git remote:"
          cd /var/www/listerino && git remote -v